# Generated by Django 6.0 on 2025-12-10 16:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ModeOperatoire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('opération', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Periode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Poste',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenancePreventive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activite', models.CharField(max_length=200)),
                ('durree', models.FloatField(null=True)),
                ('etatMachine', models.BooleanField(default=0)),
                ('priorite', models.IntegerField()),
                ('coutPrevue', models.CharField(max_length=15)),
                ('dateTimeCreation', models.DateTimeField(auto_now=True)),
                ('dateTimeDemarrageComptage', models.DateTimeField(null=True)),
                ('dateTimeNextIntervention', models.DateTimeField(null=True)),
                ('equipement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='equipements', to='maintenance.equipement')),
                ('modeOperatoire', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modeOperatoires', to='maintenance.modeoperatoire')),
                ('periode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodes', to='maintenance.periode')),
                ('agent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agents', to='maintenance.poste')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='maintenance.section')),
            ],
        ),
        migrations.AddField(
            model_name='equipement',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='EquipementSections', to='maintenance.section'),
        ),
    ]
