# Generated by Django 6.0 on 2025-12-15 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='modeoperatoire',
            old_name='opération',
            new_name='operation',
        ),
    ]
